// AUTO-GENERATED by scripts/bundle-migrations.js — DO NOT EDIT MANUALLY
// This stub is committed so TypeScript can resolve the import during type-checking.
// It is overwritten with real migration SQL when you run:
//   node scripts/bundle-migrations.js
// (called automatically by `npm run build:binary`)
 
export interface BundledMigration {
  name: string;
  sql: string;
}
 
export const MIGRATIONS: BundledMigration[] = [];
 