"""
Pydantic models that mirror the Graphyne TypeScript type definitions.

Source of truth: graphyne-client/src/types/canvas.ts
These must stay in sync with CanvasElement, CanvasConfig, AnimationConfig.
"""

from __future__ import annotations
from typing import Literal, Optional
from pydantic import BaseModel, Field, ValidationInfo, field_validator
import re


# ── Mirrors: AnimationConfig ──────────────────────────────────────────────────

class AnimationConfig(BaseModel):
    type: Literal['fade', 'slide-left', 'slide-right', 'slide-up', 'slide-down', 'scale']
    duration: float = Field(ge=0.1, le=10.0, description="Duration in seconds")
    delay: float    = Field(ge=0.0, le=10.0, default=0.0)
    ease: str       = Field(default="power2.out")


# ── Mirrors: ShadowEffect ─────────────────────────────────────────────────────

class ShadowEffect(BaseModel):
    color: str
    blur: float   = Field(ge=0)
    offsetX: float
    offsetY: float


# ── Mirrors: CanvasElement ────────────────────────────────────────────────────

class CanvasElement(BaseModel):
    id: str         = Field(description="UUID for this element — generated by the pipeline")
    type: Literal['rect', 'circle', 'text', 'image']
    name: str       = Field(description="Human-readable layer name, e.g. 'Background Bar'")

    # Transform
    x: float
    y: float
    width: float  = Field(gt=0)
    height: float = Field(gt=0)
    rotation: float = Field(default=0.0)
    scaleX: float   = Field(default=1.0, gt=0)
    scaleY: float   = Field(default=1.0, gt=0)
    zIndex: int     = Field(default=0, ge=0)

    # Appearance — fill is always required
    fill: str       = Field(description="Hex color. For image elements, use 'transparent'.")
    opacity: float  = Field(default=1.0, ge=0.0, le=1.0)
    stroke: Optional[str]       = None
    strokeWidth: Optional[float]= Field(default=None, gt=0)
    cornerRadius: Optional[float] = Field(default=None, ge=0)

    # Text
    text: Optional[str]         = None
    fontSize: Optional[float]   = Field(default=None, gt=0)
    fontFamily: Optional[str]   = None
    fontWeight: Optional[str]   = None
    align: Optional[Literal['left', 'center', 'right']] = None

    # Image
    src: Optional[str]          = None

    # Effects
    shadow: Optional[ShadowEffect] = None

    # State
    isVisible: bool = True
    isLocked: bool  = False

    # Animations
    inAnimation: Optional[AnimationConfig]  = None
    outAnimation: Optional[AnimationConfig] = None

    @field_validator('fill')
    @classmethod
    def validate_hex_color(cls, v: str) -> str:
        """Ensure fill is a valid hex color or 'transparent'."""
        if v == 'transparent':
            return v
        if not re.match(r'^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$', v):
            raise ValueError(f"fill must be a hex color (e.g. #FF0000) or 'transparent', got: {v!r}")
        return v

    @field_validator('src')
    @classmethod
    def image_must_have_src(cls, v: Optional[str], info: ValidationInfo) -> Optional[str]:
        """Images that have a src must be a valid URL or data URI."""
        if v is not None and not (v.startswith('http') or v.startswith('data:')):
            raise ValueError("src must be a URL or data URI")
        return v


# ── Mirrors: CanvasConfig ─────────────────────────────────────────────────────

class CanvasConfig(BaseModel):
    width: float  = Field(default=1920, gt=0)
    height: float = Field(default=1080, gt=0)
    background: str = Field(default='transparent')

    @field_validator('background')
    @classmethod
    def validate_background(cls, v: str) -> str:
        if v == 'transparent':
            return v
        if not re.match(r'^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', v):
            raise ValueError(f"background must be a hex color or 'transparent', got: {v!r}")
        return v


# ── The full graphic state — what gets POSTed to /api/graphics ───────────────

class GraphicDesign(BaseModel):
    """
    The complete output of the LLM pipeline.
    """
    name: str = Field(description="A short display name for this graphic")
    config: CanvasConfig
    elements: list[CanvasElement] = Field(min_length=1, description="At least one element required")

    def validate_element_rules(self) -> list[str]:
        """
        Cross-element business rules that Pydantic field validators can't catch.
        Returns a list of warning strings (not errors — the LLM might get these wrong).
        """
        warnings = []

        for el in self.elements:
            # Image elements must use fill='transparent'
            if el.type == 'image' and el.fill != 'transparent':
                warnings.append(
                    f"Element '{el.name}' is type 'image' but fill is '{el.fill}' — should be 'transparent'"
                )
            # Text elements must have text content
            if el.type == 'text' and not el.text:
                warnings.append(f"Element '{el.name}' is type 'text' but has no text content")

            # Bounds check — element shouldn't be entirely off-canvas
            if el.x > self.config.width or el.y > self.config.height:
                warnings.append(
                    f"Element '{el.name}' at ({el.x}, {el.y}) is outside the canvas "
                    f"({self.config.width}x{self.config.height})"
                )

        # Check for duplicate IDs
        ids = [el.id for el in self.elements]
        if len(ids) != len(set(ids)):
            warnings.append("Duplicate element IDs detected — elements may overwrite each other")

        return warnings